/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type ExternalBlob = Uint8Array;
export interface LiveStream {
  'id' : string,
  'startTime' : Time,
  'status' : LiveStreamStatus,
  'title' : string,
  'producerId' : Principal,
  'description' : string,
  'story' : string,
}
export type LiveStreamStatus = { 'scheduled' : null } |
  { 'active' : null } |
  { 'ended' : null };
export interface Order {
  'id' : string,
  'razorpayPaymentId' : [] | [string],
  'status' : OrderStatus,
  'productId' : string,
  'timestamp' : Time,
  'quantity' : bigint,
  'buyer' : Principal,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export interface Producer {
  'id' : Principal,
  'bio' : string,
  'region' : string,
  'verified' : boolean,
  'brandLogoBlob' : [] | [ExternalBlob],
  'rarityBadge' : string,
  'name' : string,
  'profilePhoto' : [] | [ExternalBlob],
  'whatsApp' : string,
  'voiceStoryBlob' : [] | [ExternalBlob],
  'brandTagline' : string,
  'followerCount' : bigint,
  'brandName' : string,
  'brandColor' : string,
}
export interface Product {
  'id' : string,
  'region' : string,
  'voiceNote' : [] | [ExternalBlob],
  'title' : string,
  'rarityBadge' : string,
  'thumbnail' : [] | [ExternalBlob],
  'liveVideoURL' : [] | [string],
  'producerId' : Principal,
  'description' : string,
  'stock' : bigint,
  'rarityCountdownEnd' : [] | [bigint],
  'price' : bigint,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminApproveProducer' : ActorMethod<[Principal], boolean>,
  'adminRejectProducer' : ActorMethod<[Principal], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelOrder' : ActorMethod<[string], undefined>,
  'createLiveStream' : ActorMethod<[string, string, Time], string>,
  'createOrUpdateProducer' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [ExternalBlob],
      string,
      string,
      [] | [ExternalBlob],
      string,
      [] | [ExternalBlob],
      string,
      string,
    ],
    undefined
  >,
  'createOrUpdateProduct' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      string,
      bigint,
      [] | [ExternalBlob],
      [] | [ExternalBlob],
      string,
      [] | [bigint],
      [] | [string],
    ],
    undefined
  >,
  'createOrder' : ActorMethod<[string, bigint, [] | [string]], string>,
  'deleteProducer' : ActorMethod<[Principal], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'followProducer' : ActorMethod<[Principal], undefined>,
  'getAllLiveStreams' : ActorMethod<[], Array<LiveStream>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducers' : ActorMethod<[], Array<Producer>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFollowerCount' : ActorMethod<[Principal], bigint>,
  'getLiveStream' : ActorMethod<[string], LiveStream>,
  'getLiveStreamsByProducer' : ActorMethod<[Principal], Array<LiveStream>>,
  'getLiveStreamsByRegions' : ActorMethod<[Array<string>], Array<LiveStream>>,
  'getLiveStreamsByStatus' : ActorMethod<[LiveStreamStatus], Array<LiveStream>>,
  'getOrder' : ActorMethod<[string], Order>,
  'getOrdersByBuyer' : ActorMethod<[], Array<Order>>,
  'getOrdersByProduct' : ActorMethod<[string], Array<Order>>,
  'getOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'getProducer' : ActorMethod<[Principal], Producer>,
  'getProducersByRegion' : ActorMethod<[string], Array<Producer>>,
  'getProduct' : ActorMethod<[string], Product>,
  'getProductsByBrandName' : ActorMethod<[string], Array<Product>>,
  'getProductsByPriceRange' : ActorMethod<[bigint, bigint], Array<Product>>,
  'getProductsByProducer' : ActorMethod<[Principal], Array<Product>>,
  'getProductsByRarityBadge' : ActorMethod<[string], Array<Product>>,
  'getProductsByRegion' : ActorMethod<[string], Array<Product>>,
  'getProductsByVerifiedProducer' : ActorMethod<[Principal], Array<Product>>,
  'getProductsInStock' : ActorMethod<[], Array<Product>>,
  'getProductsWithLiveVideo' : ActorMethod<[], Array<Product>>,
  'getRegionalProductsByProducer' : ActorMethod<
    [Principal, string],
    Array<Product>
  >,
  'getUniqueRegions' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVerifiedProducerProducts' : ActorMethod<[Principal], Array<Product>>,
  'getVerifiedProducers' : ActorMethod<[], Array<Producer>>,
  'getVerifiedProducts' : ActorMethod<[], Array<Product>>,
  'getVerifiedProductsByRegion' : ActorMethod<[string], Array<Product>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[Principal, Principal], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'unfollowProducer' : ActorMethod<[Principal], undefined>,
  'updateLiveStreamStatus' : ActorMethod<[string, LiveStreamStatus], undefined>,
  'updateLiveStreamStory' : ActorMethod<[string, string], undefined>,
  'updateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];