/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const LiveStreamStatus = IDL.Variant({
  'scheduled' : IDL.Null,
  'active' : IDL.Null,
  'ended' : IDL.Null,
});
export const LiveStream = IDL.Record({
  'id' : IDL.Text,
  'startTime' : Time,
  'status' : LiveStreamStatus,
  'title' : IDL.Text,
  'producerId' : IDL.Principal,
  'description' : IDL.Text,
  'story' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'razorpayPaymentId' : IDL.Opt(IDL.Text),
  'status' : OrderStatus,
  'productId' : IDL.Text,
  'timestamp' : Time,
  'quantity' : IDL.Int,
  'buyer' : IDL.Principal,
});
export const Producer = IDL.Record({
  'id' : IDL.Principal,
  'bio' : IDL.Text,
  'region' : IDL.Text,
  'verified' : IDL.Bool,
  'brandLogoBlob' : IDL.Opt(ExternalBlob),
  'rarityBadge' : IDL.Text,
  'name' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'whatsApp' : IDL.Text,
  'voiceStoryBlob' : IDL.Opt(ExternalBlob),
  'brandTagline' : IDL.Text,
  'followerCount' : IDL.Nat,
  'brandName' : IDL.Text,
  'brandColor' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'region' : IDL.Text,
  'voiceNote' : IDL.Opt(ExternalBlob),
  'title' : IDL.Text,
  'rarityBadge' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'liveVideoURL' : IDL.Opt(IDL.Text),
  'producerId' : IDL.Principal,
  'description' : IDL.Text,
  'stock' : IDL.Int,
  'rarityCountdownEnd' : IDL.Opt(IDL.Int),
  'price' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminApproveProducer' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'adminRejectProducer' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelOrder' : IDL.Func([IDL.Text], [], []),
  'createLiveStream' : IDL.Func([IDL.Text, IDL.Text, Time], [IDL.Text], []),
  'createOrUpdateProducer' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Text,
        IDL.Opt(ExternalBlob),
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'createOrUpdateProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Int,
        IDL.Opt(ExternalBlob),
        IDL.Opt(ExternalBlob),
        IDL.Text,
        IDL.Opt(IDL.Int),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'deleteProducer' : IDL.Func([IDL.Principal], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'followProducer' : IDL.Func([IDL.Principal], [], []),
  'getAllLiveStreams' : IDL.Func([], [IDL.Vec(LiveStream)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducers' : IDL.Func([], [IDL.Vec(Producer)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFollowerCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getLiveStream' : IDL.Func([IDL.Text], [LiveStream], ['query']),
  'getLiveStreamsByProducer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(LiveStream)],
      ['query'],
    ),
  'getLiveStreamsByRegions' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [IDL.Vec(LiveStream)],
      ['query'],
    ),
  'getLiveStreamsByStatus' : IDL.Func(
      [LiveStreamStatus],
      [IDL.Vec(LiveStream)],
      ['query'],
    ),
  'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
  'getOrdersByBuyer' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrdersByProduct' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
  'getProducer' : IDL.Func([IDL.Principal], [Producer], ['query']),
  'getProducersByRegion' : IDL.Func([IDL.Text], [IDL.Vec(Producer)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProductsByBrandName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsByPriceRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsByProducer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsByRarityBadge' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsByRegion' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getProductsByVerifiedProducer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getProductsInStock' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsWithLiveVideo' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getRegionalProductsByProducer' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUniqueRegions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVerifiedProducerProducts' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getVerifiedProducers' : IDL.Func([], [IDL.Vec(Producer)], ['query']),
  'getVerifiedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getVerifiedProductsByRegion' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func(
      [IDL.Principal, IDL.Principal],
      [IDL.Bool],
      ['query'],
    ),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'unfollowProducer' : IDL.Func([IDL.Principal], [], []),
  'updateLiveStreamStatus' : IDL.Func([IDL.Text, LiveStreamStatus], [], []),
  'updateLiveStreamStory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const LiveStreamStatus = IDL.Variant({
    'scheduled' : IDL.Null,
    'active' : IDL.Null,
    'ended' : IDL.Null,
  });
  const LiveStream = IDL.Record({
    'id' : IDL.Text,
    'startTime' : Time,
    'status' : LiveStreamStatus,
    'title' : IDL.Text,
    'producerId' : IDL.Principal,
    'description' : IDL.Text,
    'story' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'razorpayPaymentId' : IDL.Opt(IDL.Text),
    'status' : OrderStatus,
    'productId' : IDL.Text,
    'timestamp' : Time,
    'quantity' : IDL.Int,
    'buyer' : IDL.Principal,
  });
  const Producer = IDL.Record({
    'id' : IDL.Principal,
    'bio' : IDL.Text,
    'region' : IDL.Text,
    'verified' : IDL.Bool,
    'brandLogoBlob' : IDL.Opt(ExternalBlob),
    'rarityBadge' : IDL.Text,
    'name' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'whatsApp' : IDL.Text,
    'voiceStoryBlob' : IDL.Opt(ExternalBlob),
    'brandTagline' : IDL.Text,
    'followerCount' : IDL.Nat,
    'brandName' : IDL.Text,
    'brandColor' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'region' : IDL.Text,
    'voiceNote' : IDL.Opt(ExternalBlob),
    'title' : IDL.Text,
    'rarityBadge' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'liveVideoURL' : IDL.Opt(IDL.Text),
    'producerId' : IDL.Principal,
    'description' : IDL.Text,
    'stock' : IDL.Int,
    'rarityCountdownEnd' : IDL.Opt(IDL.Int),
    'price' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminApproveProducer' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'adminRejectProducer' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelOrder' : IDL.Func([IDL.Text], [], []),
    'createLiveStream' : IDL.Func([IDL.Text, IDL.Text, Time], [IDL.Text], []),
    'createOrUpdateProducer' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'createOrUpdateProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Int,
          IDL.Opt(ExternalBlob),
          IDL.Opt(ExternalBlob),
          IDL.Text,
          IDL.Opt(IDL.Int),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'deleteProducer' : IDL.Func([IDL.Principal], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'followProducer' : IDL.Func([IDL.Principal], [], []),
    'getAllLiveStreams' : IDL.Func([], [IDL.Vec(LiveStream)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducers' : IDL.Func([], [IDL.Vec(Producer)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFollowerCount' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getLiveStream' : IDL.Func([IDL.Text], [LiveStream], ['query']),
    'getLiveStreamsByProducer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(LiveStream)],
        ['query'],
      ),
    'getLiveStreamsByRegions' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [IDL.Vec(LiveStream)],
        ['query'],
      ),
    'getLiveStreamsByStatus' : IDL.Func(
        [LiveStreamStatus],
        [IDL.Vec(LiveStream)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Text], [Order], ['query']),
    'getOrdersByBuyer' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrdersByProduct' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
    'getProducer' : IDL.Func([IDL.Principal], [Producer], ['query']),
    'getProducersByRegion' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Producer)],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProductsByBrandName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByPriceRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByProducer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByRarityBadge' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByRegion' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getProductsByVerifiedProducer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsInStock' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsWithLiveVideo' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getRegionalProductsByProducer' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUniqueRegions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVerifiedProducerProducts' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getVerifiedProducers' : IDL.Func([], [IDL.Vec(Producer)], ['query']),
    'getVerifiedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getVerifiedProductsByRegion' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func(
        [IDL.Principal, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'unfollowProducer' : IDL.Func([IDL.Principal], [], []),
    'updateLiveStreamStatus' : IDL.Func([IDL.Text, LiveStreamStatus], [], []),
    'updateLiveStreamStory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };